import React, { useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import {
  ArrowLeft,
  Download,
  FileText,
  Activity,
  Heart,
  Thermometer,
  Brain,
  Sparkles,
} from "lucide-react";

const ReportViewer = () => {
  const navigate = useNavigate();
  const { reportId } = useParams();
  const [showAiAnalysis, setShowAiAnalysis] = useState(true);

  const reportData = {
    patientName: "John Doe",
    age: 32,
    gender: "Male",
    date: "2024-01-10",
    hospital: "City General Hospital",
    doctor: "Dr. Smith",
    tests: [
      {
        name: "Hemoglobin",
        value: "10.2 g/dL",
        normalRange: "13.5-17.5 g/dL",
        status: "low",
      },
      {
        name: "Glucose",
        value: "95 mg/dL",
        normalRange: "70-100 mg/dL",
        status: "normal",
      },
      {
        name: "Cholesterol",
        value: "240 mg/dL",
        normalRange: "<200 mg/dL",
        status: "high",
      },
      {
        name: "Blood Pressure",
        value: "130/85 mmHg",
        normalRange: "<120/80 mmHg",
        status: "borderline",
      },
      {
        name: "WBC Count",
        value: "7,500 cells/µL",
        normalRange: "4,500-11,000 cells/µL",
        status: "normal",
      },
    ],
    aiAnalysis: {
      summary:
        "Your blood report shows mild anemia and high cholesterol levels. Other parameters are within normal range.",
      recommendations: [
        "Consult a hematologist for low hemoglobin levels",
        "Follow a cholesterol-lowering diet",
        "Increase iron-rich foods in your diet",
        "Schedule a follow-up in 2 weeks",
      ],
      riskLevel: "Moderate",
      nextSteps: "Schedule appointment with Dr. Smith",
    },
  };

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white shadow-sm">
        <div className="max-w-6xl mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <button
              onClick={() => navigate("/dashboard")}
              className="flex items-center gap-2 text-gray-600 hover:text-blue-600 transition"
            >
              <ArrowLeft size={20} />
              Back to Dashboard
            </button>
            <div className="flex items-center gap-4">
              <button className="flex items-center gap-2 px-4 py-2 border border-blue-600 text-blue-600 rounded-lg hover:bg-blue-50 transition">
                <Download size={16} />
                Download PDF
              </button>
              <button
                onClick={() => setShowAiAnalysis(!showAiAnalysis)}
                className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition"
              >
                <Sparkles size={16} />
                {showAiAnalysis ? "Hide AI Analysis" : "Show AI Analysis"}
              </button>
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-6 py-8">
        <div className="grid lg:grid-cols-3 gap-8">
          {/* Report Content */}
          <div className="lg:col-span-2">
            <div className="bg-white rounded-2xl shadow-sm p-8 mb-6">
              <div className="flex items-start justify-between mb-8">
                <div>
                  <h1 className="text-3xl font-bold text-gray-900 mb-2">
                    Complete Blood Report
                  </h1>
                  <div className="flex items-center gap-6 text-gray-600">
                    <div className="flex items-center gap-2">
                      <FileText size={16} />
                      Report ID: {reportId}
                    </div>
                    <div className="flex items-center gap-2">
                      <Activity size={16} />
                      {reportData.date}
                    </div>
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-lg font-semibold">
                    {reportData.patientName}
                  </div>
                  <div className="text-sm text-gray-600">
                    {reportData.age} years, {reportData.gender}
                  </div>
                </div>
              </div>

              <div className="mb-8 p-6 bg-blue-50 rounded-xl">
                <div className="flex items-center gap-4 mb-4">
                  <div className="w-12 h-12 bg-white rounded-lg flex items-center justify-center">
                    <Activity className="text-blue-600" size={24} />
                  </div>
                  <div>
                    <h3 className="font-bold text-lg">Test Results Summary</h3>
                    <p className="text-gray-600">
                      Generated by: {reportData.hospital}
                    </p>
                  </div>
                </div>
                <div className="grid grid-cols-3 gap-4">
                  <div className="text-center p-4 bg-white rounded-lg">
                    <div className="text-2xl font-bold text-green-600">3</div>
                    <div className="text-sm text-gray-600">Normal</div>
                  </div>
                  <div className="text-center p-4 bg-white rounded-lg">
                    <div className="text-2xl font-bold text-yellow-600">1</div>
                    <div className="text-sm text-gray-600">Borderline</div>
                  </div>
                  <div className="text-center p-4 bg-white rounded-lg">
                    <div className="text-2xl font-bold text-red-600">1</div>
                    <div className="text-sm text-gray-600">Abnormal</div>
                  </div>
                </div>
              </div>

              {/* Test Results */}
              <div className="space-y-6">
                <h3 className="text-2xl font-bold mb-6">Detailed Results</h3>

                {reportData.tests.map((test, index) => (
                  <div key={index} className="border rounded-xl p-6">
                    <div className="flex items-center justify-between mb-4">
                      <div className="flex items-center gap-4">
                        <div
                          className={`w-10 h-10 rounded-lg flex items-center justify-center ${
                            test.status === "normal"
                              ? "bg-green-100"
                              : test.status === "low"
                              ? "bg-yellow-100"
                              : "bg-red-100"
                          }`}
                        >
                          {test.name.includes("Blood") ? (
                            <Heart
                              className={
                                test.status === "normal"
                                  ? "text-green-600"
                                  : test.status === "low"
                                  ? "text-yellow-600"
                                  : "text-red-600"
                              }
                              size={20}
                            />
                          ) : test.name.includes("Pressure") ? (
                            <Activity
                              className={
                                test.status === "normal"
                                  ? "text-green-600"
                                  : test.status === "low"
                                  ? "text-yellow-600"
                                  : "text-red-600"
                              }
                              size={20}
                            />
                          ) : test.name.includes("Glucose") ? (
                            <Thermometer
                              className={
                                test.status === "normal"
                                  ? "text-green-600"
                                  : test.status === "low"
                                  ? "text-yellow-600"
                                  : "text-red-600"
                              }
                              size={20}
                            />
                          ) : (
                            <Brain
                              className={
                                test.status === "normal"
                                  ? "text-green-600"
                                  : test.status === "low"
                                  ? "text-yellow-600"
                                  : "text-red-600"
                              }
                              size={20}
                            />
                          )}
                        </div>
                        <div>
                          <h4 className="font-bold text-lg">{test.name}</h4>
                          <p className="text-gray-600 text-sm">
                            Normal range: {test.normalRange}
                          </p>
                        </div>
                      </div>
                      <div className="text-right">
                        <div
                          className={`text-2xl font-bold ${
                            test.status === "normal"
                              ? "text-green-600"
                              : test.status === "low"
                              ? "text-yellow-600"
                              : "text-red-600"
                          }`}
                        >
                          {test.value}
                        </div>
                        <span
                          className={`px-3 py-1 rounded-full text-sm ${
                            test.status === "normal"
                              ? "bg-green-100 text-green-800"
                              : test.status === "low"
                              ? "bg-yellow-100 text-yellow-800"
                              : "bg-red-100 text-red-800"
                          }`}
                        >
                          {test.status === "normal"
                            ? "Normal"
                            : test.status === "low"
                            ? "Below Normal"
                            : "Above Normal"}
                        </span>
                      </div>
                    </div>

                    <div className="mt-4 p-4 bg-gray-50 rounded-lg">
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-600">Your Value</span>
                        <span className="text-gray-600">Normal Range</span>
                      </div>
                      <div className="mt-2 h-2 bg-gray-200 rounded-full overflow-hidden">
                        <div
                          className={`h-full ${
                            test.status === "normal"
                              ? "bg-green-500"
                              : test.status === "low"
                              ? "bg-yellow-500"
                              : "bg-red-500"
                          }`}
                          style={{
                            width:
                              test.status === "normal"
                                ? "50%"
                                : test.status === "low"
                                ? "30%"
                                : "80%",
                          }}
                        ></div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* AI Analysis Sidebar */}
          {showAiAnalysis && (
            <div className="lg:col-span-1">
              <div className="sticky top-8">
                <div className="bg-linear-to-b from-blue-600 to-blue-700 rounded-2xl p-6 text-white mb-6">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="w-12 h-12 bg-white/20 rounded-lg flex items-center justify-center">
                      <Sparkles size={24} />
                    </div>
                    <div>
                      <h3 className="font-bold text-lg">AI Health Assistant</h3>
                      <p className="text-blue-100 text-sm">
                        Powered by PrimeHealth AI
                      </p>
                    </div>
                  </div>

                  <div className="mb-6">
                    <div className="text-sm text-blue-200 mb-2">
                      Risk Assessment
                    </div>
                    <div className="flex items-center justify-between mb-2">
                      <span>Overall Health</span>
                      <span className="font-bold">Moderate</span>
                    </div>
                    <div className="h-2 bg-white/30 rounded-full overflow-hidden">
                      <div
                        className="h-full bg-yellow-400"
                        style={{ width: "60%" }}
                      ></div>
                    </div>
                  </div>
                </div>

                <div className="bg-white rounded-2xl shadow-sm p-6">
                  <h3 className="font-bold text-lg mb-4">
                    AI Analysis Summary
                  </h3>

                  <div className="mb-6">
                    <div className="text-sm text-gray-600 mb-2">
                      Key Findings:
                    </div>
                    <p className="text-gray-800">
                      {reportData.aiAnalysis.summary}
                    </p>
                  </div>

                  <div className="mb-6">
                    <div className="text-sm text-gray-600 mb-2">
                      Recommendations:
                    </div>
                    <ul className="space-y-2">
                      {reportData.aiAnalysis.recommendations.map(
                        (rec, index) => (
                          <li key={index} className="flex items-start gap-2">
                            <div className="w-5 h-5 bg-blue-100 rounded-full flex items-center justify-center mt-0.5">
                              <span className="text-blue-600 text-xs">✓</span>
                            </div>
                            <span>{rec}</span>
                          </li>
                        )
                      )}
                    </ul>
                  </div>

                  <div className="p-4 bg-blue-50 rounded-xl">
                    <div className="text-sm text-gray-600 mb-2">
                      Next Steps:
                    </div>
                    <p className="font-medium">
                      {reportData.aiAnalysis.nextSteps}
                    </p>
                    <button className="w-full mt-4 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition">
                      Schedule Follow-up
                    </button>
                  </div>

                  <div className="mt-6 text-center">
                    <p className="text-sm text-gray-600">
                      This AI analysis is for informational purposes only.
                      Always consult with a healthcare professional.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default ReportViewer;
